# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "75ed4c634fbbd0d6b42bb78212e2e3cb"
name = "GemGrade Auth Handoff"
application_url = "https://app.gemcardshow.com"
embedded = false

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_app_proxy"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://app.gemcardshow.com/api/auth/shopify/callback"
]

[app_proxy]
url = "https://app.gemcardshow.com/api/auth/shopify/handoff"
subpath = "gemgrade"
prefix = "apps"
